var products = [
    {
      "_id": "1",
      "name": "BB Royal Sona Masoori Raw Rice/Akki",
      "image": "../assets/images/sonamasoori.jpg",
      "description":
        "25 kg (12 - 17 Months Old) ",
      "brand": "BB Royal",
      "category": "Rice & Rice Products",
      "price": 1247.50,
      "countInStock": 10,
      "rating": 4.5,
      "numReviews": 12,
    }, { 
        "_id": "2",
        "name": "BB Royal Basmati Rice ",
        "image": "../assets/images/rozanabasmati.jpg",
        "description":
          "Rozana Premium, 2x5 Kg Multipack",
        "brand": "BB Royal",
        "category": "Rice & Rice Products",
        "price": 780,
        "countInStock": 20,
        "rating": 4.3,
        "numReviews": 15,
    }
    , { 
        "_id": "3",
        "name": "BB Royal Organic-Toor Dal",
        "image": "../assets/images/organicturtoordal.jpg",
        "description":
          "2 kg",
        "brand": "BB Royal",
        "category": "Dal & Pulses",
        "price": 249,
        "countInStock": 12,
        "rating": 4.2,
        "numReviews": 18,
    }, { 
        "_id": "4",
        "name": "BB Royal Organic Kabuli Chana",
        "image": "../assets/images/kabulichana.jpg",
        "description":
          "500 g",
        "brand": "BB Royal",
        "category": "Dal & Pulses",
        "price": 83.60,
        "countInStock": 10,
        "rating": 4.6,
        "numReviews": 13,
    }, { 
        "_id": "5",
        "name": "Fresho Organic Cow Desi Ghee",
        "image": "../assets/images/cowdesighee.jpg",
        "description":
          "2x1 L (Multipack)",
        "brand": "Fresho",
        "category": "Edible Oil,Ghee",
        "price": 1368,
        "countInStock": 20,
        "rating": 4.4,
        "numReviews": 15,
    }, { 
        "_id": "6",
        "name": "Praakritik Organic Sunflower Oil",
        "image": "../assets/images/sunfloweroil.jpg",
        "description":
          "Cold Pressed, 500 ml",
        "brand": "Prakritik",
        "category": "Edible Oil,Ghee",
        "price": 275,
        "countInStock": 18,
        "rating": 4.0,
        "numReviews": 15,
    }, { 
        "_id": "7",
        "name": "The Baker's Dozen Lavash ",
        "image": "../assets/images/bru-gold.jpg",
        "description":
          "100% Wholewheat, 100 g",
        "brand": "The Baker's",
        "category": "Bakery Snacks",
        "price": 103.55,
        "countInStock": 30,
        "rating": 4.6,
        "numReviews": 19,
    }, { 
        "_id": "8",
        "name": "PRISTINE OvenOrg Multi Millet Bread Stick",
        "image": "../assets/images/multimilletbreadstick.jpg",
        "description":
          "100 g Carton",
        "brand": "PRISTINE",
        "category": "Bakery Snacks",
        "price": 55,
        "countInStock": 20,
        "rating": 4.7,
        "numReviews": 15,
    }, { 
        "_id": "9",
        "name": "Britannia Toastea",
        "image": "../assets/images/britanniatoastea.jpg",
        "description":
          "Premium Bake Rusk Toast, Teatime Snack, 182 g",
        "brand": "Britannia",
        "category": "Cookies, Rusk & Khari",
        "price": 29.41,
        "countInStock": 10,
        "rating": 4.3,
        "numReviews": 15,
    }, { 
        "_id": "10",
        "name": "NILGIRIS Biscuit",
        "image": "../assets/images/nilgirisbiscuit.jpg",
        "description":
          "Tea Cracker, No Added Sugar, 100 g",
        "brand": "NILGIRIS ",
        "category": "Cookies, Rusk & Khari ",
        "price": 35,
        "countInStock": 20,
        "rating": 4.3,
        "numReviews": 15,
    },
    {
        "_id": "11",
        "name": "Taj Mahal Tea",
        "image": "../assets/images/taj-mahal-tea.jpg",
        "description":
          "500 g",
        "brand": "Taj Mahal",
        "category": "Beverages",
        "price": 336,
        "countInStock": 15,
        "rating": 4.2,
        "numReviews": 122,
      }, { 
          "_id": "12",
          "name": "Thumbs Up Soft Drink",
          "image": "../assets/images/thums-up.jpg",
          "description":
            "750 ml Bottle",
          "brand": "Thumbs Up",
          "category": "Beverages",
          "price": 31.20,
          "countInStock": 25,
          "rating": 4.2,
          "numReviews": 173,
  
      },{ 
          "_id": "13",
          "name": "Bournvita Chocolate Health Drink",
          "image": "../assets/images/bournvita.jpg",
          "description":
            "1 kg Jar",
          "brand": "Bournvita",
          "category": "Beverages",
          "price": 370,
          "countInStock": 25,
          "rating": 4.1,
          "numReviews": 63,
  
      },{ 
          "_id": "14",
          "name": "Bru Gold Instant Coffee",
          "image": "../assets/images/bru-gold.jpg",
          "description":
            "100 g",
          "brand": "Bru",
          "category": "Beverages",
          "price": 270,
          "countInStock": 30,
          "rating": 4.5,
          "numReviews": 34,
  
      },{ 
          "_id": "15",
          "name": "Paper Boat Coconut water",
          "image": "../assets/images/paper-boat-coconut-water.jpg",
          "description":
            "12 X 200 ml Multipack",
          "brand": "Paper Boat",
          "category": "Beverages",
          "price": 416.93,
          "countInStock": 50,
          "rating": 3.9,
          "numReviews": 13,
  
      },{ 
          "_id": "16",
          "name": "MAGGI - 2 minutes instant noodles",
          "image": "../assets/images/maggi.jpg",
          "description":
            "280 g pouch",
          "brand": "Maggi",
          "category": "Snacks & Branded foods",
          "price": 43.43,
          "countInStock": 25,
          "rating": 4.2,
          "numReviews": 662,
  
      },
      { 
          "_id": "17",
          "name": "Britannia Good Day Cashew Cookies",
          "image": "../assets/images/britannia-good-day.jpg",
          "description":
            "120 g (Pack of 5)",
          "brand": "Britannia",
          "category": "Snacks and Branded foods",
          "price": 90,
          "countInStock": 30,
          "rating": 4.1,
          "numReviews": 260,
  
      },{ 
          "_id": "18",
          "name": "Lays Potato Chips - American Style Cream & Onion",
          "image": "../assets/images/lays-chips-cream-onion-flavour.jpg",
          "description":
            "2 X 115 g Multipack",
          "brand": "Lays",
          "category": "Snacks and Branded foods",
          "price": 65.65,
          "countInStock": 25,
          "rating": 4.1,
          "numReviews": 45,
  
      },{ 
          "_id": "19",
          "name": "Cadbury Oreo Biscuit - Vanilla Creme",
          "image": "../assets/images/cadbury-oreo.jpg",
          "description":
            "3 X 120 g Multipack",
          "brand": "Cadbury",
          "category": "Snacks and Branded foods",
          "price": 80.37,
          "countInStock": 15,
          "rating": 4.3,
          "numReviews": 15,
  
      },{ 
          "_id": "20",
          "name": "Kissan Mixed Fruit Jam",
          "image": "../assets/images/kissan-jam.jpg",
          "description":
            "700 g",
          "brand": "Kissan",
          "category": "Snacks and Branded foods",
          "price": 193.50,
          "countInStock": 25,
          "rating": 4.2,
          "numReviews": 28,
  
      },
      {
        "_id": 21,
        "name": "BB Royal Cold Pressed Oil",
        "image": "../assets/images/cold-pressed-virgin-coconut-oil.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "BB Royal",
        "category": "cold-pressed-virgin-coconut-oil",
        "price": 1247.5,
        "countInStock": 12,
        "rating": 4.8,
        "numReviews": 10,
      },
      {
        "_id": 22,
        "name": "Coconut Oil",
        "image": "../assets/images/coconut-oil.jpg",
        "description": "25 kg (12 - 15 Months Old) ",
        "brand": "checko",
        "category": "Food Grain and oil masala",
        "price": 1247.5,
        "countInStock": 11,
        "rating": 5.6,
        "numReviews": 11,
      },
      {
        "_id": 23,
        "name" : "Kitchen Glass and Drain",
        "image": "../assets/images/multi-brand-colin-gadget-cleaner-spray.jpg",
        "description": "26 kg (12 - 18 Months Old) ",
       "brand": "Fresho",
        "category": "Clean And Drain Item",
        "price": 1247.5,
        "countInStock": 13,
        "rating": 4.5,
        "numReviews": 12,
      },
      {
        "_id": 24,
        "name": "Kitchen Product",
        "image": "../assets/images/lizol-disinfectan.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "BB Royal",
        "category": "Groccery and clean item",
        "price": 124.5,
        "countInStock": 14,
        "rating": 4.2,
        "numReviews": 12,
      },
      {
        "_id": 25,
        "name": "fresho-orange-nagpur-regular",
        "image": "../assets/images/fresho-orange-nagpur-regular.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "BB Combo",
        "category": "Foodgrains, Oils & Masala",
        "price": 1247.5,
        "countInStock": 15,
        "rating": 3.5,
        "numReviews": 12,
      },
      {
        "_id": "26",
        "name": "fresho-apple-shimla",
        "image": "../assets/images/fresho-apple-shimla.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "Fresho",
        "category": "Fresh Fruit",
        "price": 1247.5,
        "countInStock": 18,
        "rating": 3.9,
        "numReviews": 12,
      },
      {
       "_id": "27",
        "name": "fresho-orange-nagpur-regular",
        "image": "../assets/images/10000266_27-fresho-orange-nagpur-regular.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "fresho",
        "category": "Foodgrains, Oils & Masala",
        "price": 1247.5,
        "countInStock": 20,
        "rating": 4.5,
        "numReviews": 12,
      },
      {
        "_id": 28,
        "name": "Pure Ghee",
        "image": "../assets/images/ghee.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "BB Royal",
        "category": "Ghee And Banaspati",
        "price": 1247.5,
        "countInStock": 10,
        "rating": 3.6,
        "numReviews": 12,
      },
      {
        "_id": 29,
       "name": "BB Royal Rice flour",
        "image": "../assets/images/bb-royal-rice-flour.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "BB Royal ",
        "category": "Foodgrains, Oils & Masala",
        "price": 2040.5,
        "countInStock": 10,
        "rating": 4.7,
        "numReviews": 12,
      },
      {
        "_id": 30,
        "name": "Amul Butter - Pasteurised, 500 g Carton",
        "image": "../assets/images/amulbutter.jpg",
        "description": "25 kg (12 - 17 Months Old) ",
        "brand": "Amul Butter and Margarine",
        "category": "Butter and Margarine",
        "price": 1024.5,
        "countInStock": 10,
        "rating": 4.5,
        "numReviews": 12,
      }
    
]

export default products;
